// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package gravity_sdk_types_record

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Method int32

const (
	Method_INSERT   Method = 0
	Method_UPDATE   Method = 1
	Method_DELETE   Method = 2
	Method_TRUNCATE Method = 3
)

var Method_name = map[int32]string{
	0: "INSERT",
	1: "UPDATE",
	2: "DELETE",
	3: "TRUNCATE",
}

var Method_value = map[string]int32{
	"INSERT":   0,
	"UPDATE":   1,
	"DELETE":   2,
	"TRUNCATE": 3,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}

func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0}
}

type DataType int32

const (
	DataType_BOOLEAN DataType = 0
	DataType_BINARY  DataType = 1
	DataType_STRING  DataType = 2
	DataType_UINT64  DataType = 3
	DataType_INT64   DataType = 4
	DataType_FLOAT64 DataType = 5
	DataType_ARRAY   DataType = 6
	DataType_MAP     DataType = 7
)

var DataType_name = map[int32]string{
	0: "BOOLEAN",
	1: "BINARY",
	2: "STRING",
	3: "UINT64",
	4: "INT64",
	5: "FLOAT64",
	6: "ARRAY",
	7: "MAP",
}

var DataType_value = map[string]int32{
	"BOOLEAN": 0,
	"BINARY":  1,
	"STRING":  2,
	"UINT64":  3,
	"INT64":   4,
	"FLOAT64": 5,
	"ARRAY":   6,
	"MAP":     7,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{1}
}

type SendReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReply) Reset()         { *m = SendReply{} }
func (m *SendReply) String() string { return proto.CompactTextString(m) }
func (*SendReply) ProtoMessage()    {}
func (*SendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0}
}

func (m *SendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReply.Unmarshal(m, b)
}
func (m *SendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReply.Marshal(b, m, deterministic)
}
func (m *SendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReply.Merge(m, src)
}
func (m *SendReply) XXX_Size() int {
	return xxx_messageInfo_SendReply.Size(m)
}
func (m *SendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendReply proto.InternalMessageInfo

func (m *SendReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type Record struct {
	EventName            string   `protobuf:"bytes,1,opt,name=eventName,proto3" json:"eventName,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Method               Method   `protobuf:"varint,3,opt,name=method,proto3,enum=gravity.sdk.types.record.Method" json:"method,omitempty"`
	PrimaryKey           string   `protobuf:"bytes,4,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	Fields               []*Field `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Record) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Record) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_INSERT
}

func (m *Record) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func (m *Record) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Field struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Value   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{2}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Value struct {
	Type                 DataType    `protobuf:"varint,1,opt,name=type,proto3,enum=gravity.sdk.types.record.DataType" json:"type,omitempty"`
	Value                []byte      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Map                  *MapValue   `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	Array                *ArrayValue `protobuf:"bytes,4,opt,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{3}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_BOOLEAN
}

func (m *Value) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetMap() *MapValue {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *Value) GetArray() *ArrayValue {
	if m != nil {
		return m.Array
	}
	return nil
}

type MapValue struct {
	Fields               []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapValue) Reset()         { *m = MapValue{} }
func (m *MapValue) String() string { return proto.CompactTextString(m) }
func (*MapValue) ProtoMessage()    {}
func (*MapValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{4}
}

func (m *MapValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapValue.Unmarshal(m, b)
}
func (m *MapValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapValue.Marshal(b, m, deterministic)
}
func (m *MapValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapValue.Merge(m, src)
}
func (m *MapValue) XXX_Size() int {
	return xxx_messageInfo_MapValue.Size(m)
}
func (m *MapValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MapValue.DiscardUnknown(m)
}

var xxx_messageInfo_MapValue proto.InternalMessageInfo

func (m *MapValue) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ArrayValue struct {
	Elements             []*Value `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayValue) Reset()         { *m = ArrayValue{} }
func (m *ArrayValue) String() string { return proto.CompactTextString(m) }
func (*ArrayValue) ProtoMessage()    {}
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{5}
}

func (m *ArrayValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayValue.Unmarshal(m, b)
}
func (m *ArrayValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayValue.Marshal(b, m, deterministic)
}
func (m *ArrayValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayValue.Merge(m, src)
}
func (m *ArrayValue) XXX_Size() int {
	return xxx_messageInfo_ArrayValue.Size(m)
}
func (m *ArrayValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayValue.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayValue proto.InternalMessageInfo

func (m *ArrayValue) GetElements() []*Value {
	if m != nil {
		return m.Elements
	}
	return nil
}

type TruncateRequest struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruncateRequest) Reset()         { *m = TruncateRequest{} }
func (m *TruncateRequest) String() string { return proto.CompactTextString(m) }
func (*TruncateRequest) ProtoMessage()    {}
func (*TruncateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{6}
}

func (m *TruncateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruncateRequest.Unmarshal(m, b)
}
func (m *TruncateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruncateRequest.Marshal(b, m, deterministic)
}
func (m *TruncateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruncateRequest.Merge(m, src)
}
func (m *TruncateRequest) XXX_Size() int {
	return xxx_messageInfo_TruncateRequest.Size(m)
}
func (m *TruncateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TruncateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TruncateRequest proto.InternalMessageInfo

func (m *TruncateRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type TruncateReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruncateReply) Reset()         { *m = TruncateReply{} }
func (m *TruncateReply) String() string { return proto.CompactTextString(m) }
func (*TruncateReply) ProtoMessage()    {}
func (*TruncateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{7}
}

func (m *TruncateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruncateReply.Unmarshal(m, b)
}
func (m *TruncateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruncateReply.Marshal(b, m, deterministic)
}
func (m *TruncateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruncateReply.Merge(m, src)
}
func (m *TruncateReply) XXX_Size() int {
	return xxx_messageInfo_TruncateReply.Size(m)
}
func (m *TruncateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TruncateReply.DiscardUnknown(m)
}

var xxx_messageInfo_TruncateReply proto.InternalMessageInfo

func (m *TruncateReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TruncateReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterEnum("gravity.sdk.types.record.Method", Method_name, Method_value)
	proto.RegisterEnum("gravity.sdk.types.record.DataType", DataType_name, DataType_value)
	proto.RegisterType((*SendReply)(nil), "gravity.sdk.types.record.SendReply")
	proto.RegisterType((*Record)(nil), "gravity.sdk.types.record.Record")
	proto.RegisterType((*Field)(nil), "gravity.sdk.types.record.Field")
	proto.RegisterType((*Value)(nil), "gravity.sdk.types.record.Value")
	proto.RegisterType((*MapValue)(nil), "gravity.sdk.types.record.MapValue")
	proto.RegisterType((*ArrayValue)(nil), "gravity.sdk.types.record.ArrayValue")
	proto.RegisterType((*TruncateRequest)(nil), "gravity.sdk.types.record.TruncateRequest")
	proto.RegisterType((*TruncateReply)(nil), "gravity.sdk.types.record.TruncateReply")
}

func init() { proto.RegisterFile("record.proto", fileDescriptor_bf94fd919e302a1d) }

var fileDescriptor_bf94fd919e302a1d = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x71, 0x1d, 0x3b, 0xc9, 0x24, 0x14, 0x6b, 0x84, 0x90, 0x0f, 0x08, 0x22, 0x0b, 0x89,
	0xa8, 0x07, 0x1f, 0x42, 0x29, 0xa8, 0x88, 0x83, 0xdb, 0xb8, 0x28, 0x22, 0x71, 0xaa, 0x8d, 0x8b,
	0xd4, 0xe3, 0x36, 0x19, 0x4a, 0x44, 0xe2, 0x98, 0xf5, 0x26, 0x92, 0x9f, 0x90, 0x23, 0xaf, 0x84,
	0x76, 0xd7, 0x21, 0xb9, 0xa4, 0x02, 0x6e, 0x33, 0xb3, 0xff, 0xff, 0x79, 0x76, 0x3c, 0x0b, 0x6d,
	0x41, 0xd3, 0x95, 0x98, 0x85, 0xb9, 0x58, 0xc9, 0x15, 0xfa, 0xf7, 0x82, 0x6f, 0xe6, 0xb2, 0x0c,
	0x8b, 0xd9, 0xf7, 0x50, 0x96, 0x39, 0x15, 0xa1, 0x39, 0x0f, 0x3e, 0x42, 0x73, 0x42, 0xd9, 0x8c,
	0x51, 0xbe, 0x28, 0xd1, 0x87, 0x7a, 0xb1, 0x9e, 0x4e, 0xa9, 0x28, 0x7c, 0xab, 0x63, 0x75, 0x1b,
	0x6c, 0x9b, 0xe2, 0x33, 0x70, 0x05, 0xf1, 0x62, 0x95, 0xf9, 0x47, 0x1d, 0xab, 0xdb, 0x64, 0x55,
	0x16, 0xfc, 0xb2, 0xc0, 0x65, 0x9a, 0x84, 0xcf, 0xa1, 0x49, 0x1b, 0xca, 0x64, 0xc2, 0x97, 0xa4,
	0xed, 0x4d, 0xb6, 0x2b, 0xe0, 0x53, 0x70, 0x24, 0xbf, 0x5b, 0x50, 0xe5, 0x37, 0x09, 0xbe, 0x07,
	0x77, 0x49, 0xf2, 0xdb, 0x6a, 0xe6, 0xdb, 0x1d, 0xab, 0x7b, 0xdc, 0xeb, 0x84, 0x87, 0x1a, 0x0d,
	0x47, 0x5a, 0xc7, 0x2a, 0x3d, 0xbe, 0x00, 0xc8, 0xc5, 0x7c, 0xc9, 0x45, 0xf9, 0x99, 0x4a, 0xbf,
	0xa6, 0xa1, 0x7b, 0x15, 0x7c, 0x07, 0xee, 0xd7, 0x39, 0x2d, 0x66, 0x85, 0xef, 0x74, 0xec, 0x6e,
	0xab, 0xf7, 0xf2, 0x30, 0xf9, 0x4a, 0xe9, 0x58, 0x25, 0x0f, 0x18, 0x38, 0xba, 0x80, 0x08, 0xb5,
	0x6c, 0x77, 0x15, 0x1d, 0xe3, 0x5b, 0x70, 0x36, 0x7c, 0xb1, 0x26, 0xdd, 0xee, 0x83, 0xd0, 0x2f,
	0x4a, 0xc6, 0x8c, 0x3a, 0xf8, 0x69, 0x81, 0xa3, 0x0b, 0x78, 0x06, 0x35, 0x25, 0xd3, 0xd0, 0xe3,
	0x5e, 0x70, 0xd8, 0xdf, 0xe7, 0x92, 0xa7, 0x65, 0x4e, 0x4c, 0xeb, 0xd5, 0xf8, 0xcc, 0x87, 0xd5,
	0xf8, 0xda, 0x15, 0x17, 0x4f, 0xc1, 0x5e, 0xf2, 0xbc, 0x6a, 0xe6, 0x01, 0xd8, 0x88, 0xe7, 0xa6,
	0x1f, 0x25, 0xc7, 0x73, 0x70, 0xb8, 0x10, 0xdc, 0x4c, 0xad, 0xd5, 0x7b, 0x75, 0xd8, 0x17, 0x29,
	0x59, 0x75, 0x13, 0x6d, 0x09, 0x2e, 0xa1, 0xb1, 0x85, 0xed, 0x8d, 0xd8, 0xfa, 0xb7, 0x11, 0x0f,
	0x00, 0x76, 0x64, 0xfc, 0x00, 0x0d, 0x5a, 0xd0, 0x92, 0x32, 0xf9, 0x17, 0x20, 0xd3, 0xcc, 0x1f,
	0x43, 0xf0, 0x1a, 0x9e, 0xa4, 0x62, 0x9d, 0x4d, 0xb9, 0x24, 0x46, 0x3f, 0xd6, 0x54, 0xc8, 0xdd,
	0xa6, 0x59, 0x7b, 0x9b, 0x16, 0x44, 0xf0, 0x78, 0x27, 0xfc, 0xaf, 0x5d, 0x3f, 0x39, 0x07, 0xd7,
	0x2c, 0x21, 0x02, 0xb8, 0x83, 0x64, 0x12, 0xb3, 0xd4, 0x7b, 0xa4, 0xe2, 0x9b, 0xeb, 0x7e, 0x94,
	0xc6, 0x9e, 0xa5, 0xe2, 0x7e, 0x3c, 0x8c, 0xd3, 0xd8, 0x3b, 0xc2, 0x36, 0x34, 0x52, 0x76, 0x93,
	0x5c, 0xaa, 0x13, 0xfb, 0xe4, 0x1e, 0x1a, 0xdb, 0x3f, 0x8a, 0x2d, 0xa8, 0x5f, 0x8c, 0xc7, 0xc3,
	0x38, 0x4a, 0x8c, 0xfd, 0x62, 0x90, 0x44, 0xec, 0xd6, 0xd8, 0x27, 0x29, 0x1b, 0x24, 0x9f, 0xbc,
	0x23, 0x8d, 0x1d, 0x24, 0xe9, 0xd9, 0xa9, 0x67, 0x63, 0x13, 0x1c, 0x13, 0xd6, 0x94, 0xf7, 0x6a,
	0x38, 0x8e, 0x54, 0xe2, 0xa8, 0x7a, 0xc4, 0x58, 0x74, 0xeb, 0xb9, 0x58, 0x07, 0x7b, 0x14, 0x5d,
	0x7b, 0xf5, 0x3b, 0x57, 0x3f, 0xf8, 0x37, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x55, 0x21,
	0xed, 0x00, 0x04, 0x00, 0x00,
}
